services:
  nacos:
    image: nacos/nacos-server:v2.5.1
    container_name: nacos-server
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./nacos/logs:/home/nacos/logs
      - ./nacos/data:/home/nacos/data
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_ACCOUNT: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: aimo_user_service
      TZ: Asia/Shanghai
    ports:
      - "3336:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    restart: always

  redis:
    image: redis:6.2.6
    container_name: redis-server
    environment:
      TZ: Asia/Shanghai
      REDIS_PASSWORD: 123456
    command: redis-server --requirepass root
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    restart: always

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq-server
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  minio:
    image: minio/minio
    container_name: minio-server
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    restart: always